# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmda', '0002_auto_20171120_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaggregate',
            name='files',
            field=models.ManyToManyField(to='mmda.FileMetadata'),
        ),
    ]
