# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmda', '0003_dataaggregate_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetadata',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
