# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmda', '0004_filemetadata_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmda.Category')),
            ],
        ),
        migrations.AddField(
            model_name='dataaggregate',
            name='categories',
            field=models.ManyToManyField(to='mmda.Category'),
        ),
    ]
