# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmda', '0007_auto_20171128_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaggregate',
            name='parent_dagr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mmda.DataAggregate'),
        ),
    ]
